### ISSUE TITLE
Mitigate argument exceptions by overwriting response headers when serving from cache

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/ResponseCaching#103]
Back port fix in #101 to 1.1.1

**Comment by JunTaoLuo** [comment]
cc @Eilon

**Comment by Eilon** [comment]
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.

**Comment by JunTaoLuo** [comment]
Changes merged. Updating version numbers now.
