### ISSUE TITLE
Mitigate argument exceptions by overwriting response headers when serving from cache

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/ResponseCaching#104]
Back port fix in #101 to 1.0.1.

cc @Eilon

**Comment by Eilon** [comment]
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.

**Comment by Eilon** [comment]
Do it.

**Comment by JunTaoLuo** [comment]
And #103? @Eilon

**Comment by JunTaoLuo** [comment]
Version numbers updated
