### ISSUE TITLE
Create a Middleware to propose an implementation of 'IHttpSendFileFeature'

### ISSUE THREAD

**Issue by Yves57** [aspnet/ResponseCaching#11]
Better repository for issue aspnet/KestrelHttpServer#981...
I have made some performance tests to see the difference between using a cache and using directly a physical file stream.
- When using a cache, I use a dictionary to store the last modification date (in case of the file is modified) and the file content.
- When using directly the file, I have more or less copy/paste the `StaticFiles.StaticFileContext` code (including `StreamCopyOperation.CopyToAsync()`).
  I created a Console application, and I made tries with different file sizes. For each file size, I loop 1000 times on the same file to copy it to the `Null` stream (to avoid uninteresting overhead). So it is the most favorable case for the physical file stream, because Windows and the hard disc can do the best use of their caches.

Here are the results on my computer:

```
Test with cache
10K --> 52 ms
30K --> 38 ms
100K --> 36 ms
500K --> 35 ms
1M --> 36 ms
5M --> 42 ms
10M --> 51 ms

Test direct stream
10K --> 148 ms
30K --> 132 ms
100K --> 179 ms
500K --> 425 ms
1M --> 728 ms
5M --> 4138 ms
10M --> 8525 ms
```

The performance difference is significant!

So I suggest to add a middleware with the following options:

```
public class SendPhysicalFileCacheOptions
{
   public int CacheMaximumSize { get; set; }   // The maximum dedicated size in MB (i.e. the sum of all file contents)
   public long FileMaximumSize { get; set; }   // The maximum size of a file to be saved in cache in Bytes (so lower than CacheMaximumSize)
   public IEnumerable<Func<string, long, bool>> Filters { get; set; } // Optional filters F(filePath, fileLength)->bool that allows user the reject files from cache
}
```

**Comment by Yves57** [comment]
Any chance for a PR on this issue to be accepted?

**Comment by Tratcher** [comment]
@JunTaoLuo has just started active work on this repo. Give us a week or two to sort out the overall design we want for response caching, then we can see where this fits.

**Comment by Yves57** [comment]
I have a an alternative idea, perhaps more elegant. Instead of creating a middleware, it is possible to create a `MemoryCacheFileProvider` (that implements `IFileProvider`) in FileSystem:
- No additionnal middleware in the middleware stack.
- it let the `IHttpSendFileFeature` interface free to be implemented.
- it authorize the user to setup the cache parameters file provider by file provider.
- it works with any kind of file provider, not just the physical file provider.
- it can be used in other file access scenarios

The source code should be something like:
```
var fileProvider = new PhysicalFileProvider(....);
var cacheProvider = new MemoryCacheFileProvider(fileProvider, options);
```

**Comment by davidfowl** [comment]
@Yves57 been meaning to file that bug forever ago https://github.com/aspnet/FileSystem/issues/219. @pakrym Did some profiling and we came to the conclusion that caching file access (with come configuration knobs) would benefit static files.

**Comment by Yves57** [comment]
@davidfowl Yes, I think it could dramatically improve performance in some scenarios.
And what is your favorite architecture:
- An implementation of `IHttpSendFileFeature` with a cache inside?
- A `MemoryCacheFileProvider` used on top of every kind of file provider?
- An optimization local to `PhysicalFileProvider`?
- Other?

**Comment by davidfowl** [comment]
> A MemoryCacheFileProvider used on top of every kind of file provider?

Leaning towards this one.

**Comment by Tratcher** [comment]
It depends, the costs are very specific to the different providers. E.g. File.Exists is very slow in PhysicalFileProvider, but I doubt EmbeddedFileProvider has the same issue. Caching just the file metadata in Physical may give us enough of a gain where caching the whole file would require significantly more resources.

**Comment by davidfowl** [comment]
Yea, of course this is all based on measurements (which we have now). I'd say we start caching fileinfos (existence checks included) then look at caching the file content if necessary (that's much more challenging to do efficiently).

**Comment by davidfowl** [comment]
Both can be knobs on the caching file provider without changing the underlying file provider.

**Comment by Yves57** [comment]
So I imagine `MemoryCacheFileProvider` could be:

```
class MemoryCacheFileProvider : IFileProvider, IDisposable
{
    public MemoryCacheFileProvider(IFileProvider innerProvider, MemoryCacheFileProviderOptions options);
    public int FileInfoCount { get; }   // Number of files currently in the cache (for statistics)
    public long ContentSize { get; }       // The cached content size in bytes (for statistics)
}

struct MemoryCacheFileProviderOptions
{
   TimeSpan DataExpiration { get; set; }   // Time during which a cache entry is considered as valid
   long MaxFileInfoCount { get; set; } // The maximum IFileInfo entries in the cache
   long MaxContentSize { get; set; }   // The maximum cumulated file content sizes, in bytes (0 to not cache content)
   Func<string, IFileInfo, bool> ContentFilter { get; set; } // Filter (subpath, fileInfo)->Boolean than
                                           // can be used to filter files that stream don't
                                           // have to be cached
}
```

- Is a `Clean()` method necessary?
- I see the interest to disable file content cache, but I don't see the interest to disable metadata cache. Correct?
- IDisposable to free memory as soon as possible when destroyed
- A cache entry is considered valid until an expiration date (it caches the `IFileInfo` attributes). When it is not valid anymore, it is not destroyed. It must just be checked next time to see if it has changed (we won't reload file content if it has not changed).
- In a first step, only metadata cache would be implemented, not content cache.

**Comment by davidfowl** [comment]
> Is a Clean() method necessary?

Who would use it?

> I see the interest to disable file content cache, but I don't see the interest to disable metadata cache. Correct?

We can start there. Both need to be configurable, we also need to decide on the behavior when the cache and the disk are out of sync (what happens when a file exists in the cache but has been deleted from disk). There might also be some security implications here (deleted files existing when they shouldn't etc).

> IDisposable to free memory as soon as possible when destroyed

Who disposes the file provider and when in the primary use case (Razor pages and static files).

> A cache entry is considered valid until an expiration date (it caches the IFileInfo attributes). When it is not valid anymore, it is not destroyed. It must just be checked next time to see if it has changed (we won't reload file content if it has not changed).

We'll need to expose the caching options on the cache entry itself for full flexibility. 

>In a first step, only metadata cache would be implemented, not content cache.

+1

**Comment by davidfowl** [comment]
Lets move this discussion to https://github.com/aspnet/FileSystem/issues/219
