### ISSUE TITLE
Allow us to override the method used to determine if response should be served from cache

### ISSUE THREAD

**Issue by coonmoo** [aspnet/ResponseCaching#110]
Hello,

please allow us to override the method used to determine if response should be served from Cache.

If e.g. a browser requests the page with the header "Cache-Control: no-cache" the page won't be served from cache. But we want to override this behaviour, to always let aspnet serve the request from the cache.

Otherwise malicious users could cause uneccessary load on the Server.

Thank you

**Comment by JunTaoLuo** [comment]
We plan on adding support for this. Tracking in #96.
