### ISSUE TITLE
feature request - set s-maxage via ResponseCacheAttribute

### ISSUE THREAD

**Issue by jimasp** [aspnet/ResponseCaching#119]
We can set max-age via the ResponseCacheAttribute.Duration property.
Could we have a corresponding property to set s-maxage?

**Comment by Tratcher** [comment]
That attribute lives in MVC: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ResponseCacheAttribute.cs
Please move this request over there.

**Comment by JunTaoLuo** [comment]
This issue was moved to aspnet/Mvc#6173
