### ISSUE TITLE
Caching response with Authorization header

### ISSUE THREAD

**Issue by bohdyone** [aspnet/ResponseCaching#128]
Looks like caching not supported if Authorization header is present. This is different to the spec, in that Public responses may still be cached even with this header. This use case is useful if you have a static app token in the Authorization header and set the Vary header to vary based on Authorization.

**Comment by RehanSaeed** [comment]
The `ResponseCachingPolicyProvider` stops all requests with an Authorization HTTP header from being cached. There are totally valid reasons for wanting to do this e.g. Writing an API with OAuth to protect it where no endpoints are user specific. Even in websites where any endpoint is not user specific but a user happens to be logged in.

When the Authorization HTTP header is present, the cached entry should be taken, the Authorization and Set-Cookie HTTP headers on it should be updated from the current request and the response returned. https://github.com/aspnet/ResponseCaching/issues/52 would mean we could do this ourselves but I think the above should be built in.

**Comment by mabakay** [comment]
@RehanSaeed you're asking wrong questions. Caching response isn't connected with presence of some headers but if served response is customisable or not (e.g., whole server need authentication, but it response with common data for everyone).
