### ISSUE TITLE
Updating cached vary by rules need to set the correct expiration

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/ResponseCaching#133]
Currently it uses the expiration information from the newer entry but this is incorrect since the entry being replaced may have a longer expiration. This could potentially lead to the situation where a valid cached response remains in the cache but the vary by rule entry that is used to retrieve it is expired and removed from the cache.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2605
