### ISSUE TITLE
VaryByCustom

### ISSUE THREAD

**Issue by AdnanCukur** [aspnet/ResponseCaching#140]
I have a Claim in my ClaimsPrincipal object, it contains a boolean, and I need the response cache to vary by this boolean. 

In MVC 5 I could easily do this with a VaryByCustom string, but I can't figure out how to solve this issue in .NET Core, is this feature missing ?

**Comment by Tratcher** [comment]
This has not been implemented. The only extension beyond HTTP caching is VaryByQueryKeys.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2602
