### ISSUE TITLE
Make constructor public to support custom IResponseCache implementations

### ISSUE THREAD

**Issue by miguelhasse** [aspnet/ResponseCaching#159]
https://github.com/aspnet/ResponseCaching/blob/d5430992d3bcf0333bcd9974558188d45ca8b489/src/Microsoft.AspNetCore.ResponseCaching/ResponseCachingMiddleware.cs#L47

**Comment by miguelhasse** [comment]
We should be able to implement and use a distributed cache for IResponseCache.

**Comment by Tratcher** [comment]
FYI: We avoided IDistributedCache on purpose. Checking the distributed cache on every request would add quite a bit of latency to your application.

**Comment by muratg** [comment]
This issue tracker is closed.
Please file issues on the Home repo as instructed by: https://github.com/aspnet/ResponseCaching/issues/149

**Comment by miguelhasse** [comment]
@Tratcher I understand your concern, but shouldn't that a decision left to however is implementing the solution that uses this library? The you're doing this also prevents even the use of a customized IMemoryCache. I have a scenario where using a custom IDistributedCache would work quite well.
