### ISSUE TITLE
Verify ResponseCaching middleware

### ISSUE THREAD

**Issue by muratg** [aspnet/ResponseCaching#18]
We plan to release this middleware in 1.1 timeline. Let's get a second pair of eyes on it.

**Comment by muratg** [comment]
cc @JunTaoLuo @Tratcher

**Comment by BrennanConroy** [comment]
BinaryReader allocates a lot, 28MB for 10000 requests, less allocations also will likely make it faster.
https://github.com/aspnet/ResponseCaching/blob/dev/src/Microsoft.AspNetCore.ResponseCaching/CacheEntry/CacheEntrySerializer.cs#L23-L26

GetDate internally allocates a lot
https://github.com/aspnet/ResponseCaching/blob/dev/src/Microsoft.AspNetCore.ResponseCaching/ResponseCachingContext.cs#L181

**Comment by BrennanConroy** [comment]
CacheControlHeader parsing allocates a ton, internally `string.ToLower` `NameValueHeaderValue` `List<NameValueHeaderValue>`

**Comment by Tratcher** [comment]
Where is there a ToLower call? That's almost always a bug.

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/HttpAbstractions/blob/e3207557342f514deea4618f595a049bfbd7a024/src/Microsoft.Net.Http.Headers/CacheControlHeaderValue.cs#L400

**Comment by muratg** [comment]
I think the initial verification is already done.
