### ISSUE TITLE
Request headers can't opt out of looking in the cache

### ISSUE THREAD

**Issue by darrelmiller** [aspnet/ResponseCaching#2]
https://github.com/aspnet/ResponseCaching/blob/chrross/initial/src/Microsoft.AspNet.ResponseCaching/CachingContext.cs#L46

No-cache in the request header says a cached response has to be revalidated.
No-store says you can't store the response, but if someone else requested it without no-store and the response is fresh then you can serve it.

Clients can avoid getting cached responses by using max-age and min-fresh request directives, but that requires pulling the  response from the cache anyway to check the age.

**Comment by JunTaoLuo** [comment]
These behaviours were not in the initial version but has since been implemented as part of #15 and #17. Thanks for keeping an eye out!
