### ISSUE TITLE
Why is path treated as case insensitive?

### ISSUE THREAD

**Issue by darrelmiller** [aspnet/ResponseCaching#3]
https://github.com/aspnet/ResponseCaching/blob/chrross/initial/src/Microsoft.AspNet.ResponseCaching/CachingContext.cs#L49

Only the host and scheme are case insensitive according to [7230](https://tools.ietf.org/html/rfc7230#section-2.7.3).  Is this an intentional deviation?

**Comment by JunTaoLuo** [comment]
Yes, for ASP.NET Core we treat the path as case-insensitively for many components such as Routing and to be consistent with those components, we are treating the path case-insensitively here as well. We may consider making this behaviour configurable if there is a need for it though.
