### ISSUE TITLE
Gated incoming requests

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/ResponseCaching#37]
In Orchard CMS, there was a feature where multiple incoming requests will block until the response for the first one is generated and is used to satisfy all waiting requests. Will need to investigate how this can be supported, either within the middleware or by the user given the available extensibility points.

cc @sebastienros

**Comment by muratg** [comment]
@sebastienros How much do you want this? Would you like to talk design, and possibly send a PR?

cc @glennc

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2623
