### ISSUE TITLE
Revalidation

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/ResponseCaching#39]
No current mechanism exist for revalidating a stale entry in the response cache. We may want to support the cache-control extensions listed in https://tools.ietf.org/html/rfc5861, in particular the `stale-while-revalidate` directive.

**Comment by muratg** [comment]
@sebastienros What's your thoughts on this? Are you able to take this one?

**Comment by sebastienros** [comment]
To me it's less important than gating, but I have some users who asked for it strongly to prevent response lags. I think we should have it on a milestone.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2621
