### ISSUE TITLE
Create feature interface for opting in/out of server side caching.

### ISSUE THREAD

**Issue by Tratcher** [aspnet/ResponseCaching#5]
Needs design

**Comment by benaadams** [comment]
Caching Attribute?

Method/Controller etc might not want to use the CacheControl header for the server in memory cache.

Or cache to disk > x Bytes; would want to integrate with static files in some way so it doesn't double cache.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2627
