### ISSUE TITLE
Change default MaximumBodySize

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/ResponseCaching#62]
Current recommended value from an offline discussion with @Tratcher and @muratg is 64MB

**Comment by BrennanConroy** [comment]
@JunTaoLuo

**Comment by muratg** [comment]
@BrennanConroy Are you taking this one?

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/ResponseCaching/commit/4e10d191756c505d48a56bcaa499954c17f7f0f1
