### ISSUE TITLE
Review logged messages

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/ResponseCaching#68]
Review the messages that are logged added in https://github.com/aspnet/ResponseCaching/pull/65. Also make sure the messages are at the correct level.

**Comment by muratg** [comment]
@glennc Were you able to look into this?

**Comment by muratg** [comment]
@glennc Are you able to look into this for preview2, or should we move it out to preview3.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2615
