### ISSUE TITLE
Cache chunked rather than whole byte[]

### ISSUE THREAD

**Issue by benaadams** [aspnet/ResponseCaching#7]
Cached data should be stored in < 85k chunks rather than as whole byte[] so they live in GC generations rather than LoH and can be cleaned without requiring a full Gen2

**Comment by benaadams** [comment]
Fragmented stream example https://github.com/Microsoft/Microsoft.IO.RecyclableMemoryStream

**Comment by JunTaoLuo** [comment]
Sharding has been implemented in https://github.com/aspnet/ResponseCaching/pull/57 for `MemoryResponseCacheStore`.

**Comment by benaadams** [comment]
@JunTaoLuo very nice, thank you!
