### ISSUE TITLE
Confusing middleware's name

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/ResponseCaching#78]
https://docs.asp.net/en/latest/performance/caching/response.html
![image](https://cloud.githubusercontent.com/assets/12871379/19714721/b3f1d286-9b50-11e6-86a4-c59c8811c916.png)

https://blogs.msdn.microsoft.com/webdev/2016/10/25/announcing-asp-net-core-1-1-preview-1/
![image](https://cloud.githubusercontent.com/assets/12871379/19714742/d83d80b8-9b50-11e6-8f63-20bb787c5422.png)

I'm not sure why you don't use Output Cache Middleware as the name, just my 2 cent

**Comment by davidfowl** [comment]
Same reason we don't use FormsAuth for what is *really* cookie auth.

**Comment by andrew-vandenbrink** [comment]
I assume this **middleware** is different with response caching **attribute**

**Comment by Tratcher** [comment]
Actually the attribute chains into the middleware. The attribute sets response caching headers and the middleware reads those headers to see if it should cache.

**Comment by andrew-vandenbrink** [comment]
```
 [ResponseCache(Duration = 600)]
```

So when I use that attribute only, it will set http max-age into browser
and when I use the middleware too, it will cache it in server's memory too?

**Comment by Tratcher** [comment]
With some restrictions, yes. The middleware will only cache responses marked as public.

**Comment by andrew-vandenbrink** [comment]
its official name now :(

**Comment by davidfowl** [comment]
Set in stone
