### ISSUE TITLE
Option for disk-backed cache

### ISSUE THREAD

**Issue by benaadams** [aspnet/ResponseCaching#8]
So when items are evicted due to memory pressure or over recycles they can be resurrected if needed without regeneration if within cache period.

Similar to [Using Static Content Generation in ASP.NET Core](http://blog.decayingcode.com/post/using-static-content-generation-in-asp.net-core/) by @MaximRouiller

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2626
