### ISSUE TITLE
Port fix for Update how certain cache directives are handled to 1.0.x

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/ResponseCaching#89]
The fix for https://github.com/aspnet/ResponseCaching/issues/83 needs to go into LTS 1.0.x branch.

**Comment by JunTaoLuo** [comment]
Need to discuss which parts of the fixes in #88 needs to be back ported to 1.0.x

At the minimum, we'll need the fix for using `If-Modified-Since` instead of the incorrect `If-Unmodified-Since`.

We can potentially also add the handling of proxy-revalidate, and max-stale with no specified limit since those are low risk but they are not critical.

**Comment by JunTaoLuo** [comment]
cc @muratg

**Comment by muratg** [comment]
(Setting milestone to 1.0.1 to reflect the actual package version to be shipped.)

**Comment by Eilon** [comment]
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.

**Comment by JunTaoLuo** [comment]
Patch merged. Will still need to update version numbers.

**Comment by JunTaoLuo** [comment]
Version numbers updated
