### ISSUE TITLE
Option for WeakReference caching 

### ISSUE THREAD

**Issue by benaadams** [aspnet/ResponseCaching#9]
So cached items can be evicted on GC rather than having infrequently accessed items remaining cached in memory until expiry (utilizing [sample for caching weak references](https://github.com/aspnet/Caching/commit/a197fe623325e67f5a9a33f759499bcd4828d235) by @Tratcher)

Related #8 "Option for disk-backed cache"

**Comment by muratg** [comment]
After doing perf investigation, we may end up bringing this back to 1.1.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2625
