### ISSUE TITLE
Port fix for Update how certain cache directives are handled to 1.1.x

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/ResponseCaching#91]
We'll need to port back part of the fixes in #88 back to 1.1.x.

At the minimum we'll need the fixes to:
- Always add the IResponseCachingFeature before calling the next middleware #81 
- Use `If-Modified-Since` instead of the wrong `If-Unmodified-Since` header for conditional requests

Also potentially consider
- handling of `proxy-revalidate` cache directive and handling of `max-stale` without specified limit

**Comment by JunTaoLuo** [comment]
cc @muratg

**Comment by Eilon** [comment]
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.

**Comment by Eilon** [comment]
@muratg please assign.

**Comment by JunTaoLuo** [comment]
Patch merged. Leaving the issue open since version numbers will need to be updated.

**Comment by JunTaoLuo** [comment]
Changes merged. Updating version numbers now.
