### ISSUE TITLE
Investigate request `no-cache` behaviour

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/ResponseCaching#95]
In the current implementation, for requests with a `no-cache` directive, cache lookup is skipped but response capture and cache store still occurs. The RFC only specifies that the cache cannot use a stored response to satisfy the request without validation but explicitly says nothing regarding the response.

This means that for requests with `no-cache`, writes to the cache will still occur and will overwrite any existing cached entries for the same resource. This can lead to a large amount of potentially wasted writes and we should determine if this behaviour is common in other implementation of HTTP caching.

Note that this can be resolved with user provided implementations of the `IResponseCachingPolicyProvider` but that is not currently exposed publicly. Regardless, we should investigate whether the current implementation should be the default behaviour.

**Comment by muratg** [comment]
Assigning to @JunTaoLuo for investigation.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2613
